language: node_js
node_js:
- '0.12'
env:
  global:
  - secure: Ewo8VALh/4wbuCzO8ibwvoKbJcX/Fo8mUgYZGwsPAv4QD9Q4aVJXZAttyJ6GjS6tiRL+QVqsWLtLaBDzp8AXtBsL9i70+chERw/EwMJhuZkEz1KgorC7JVoXAEOL5N5LqAkkmYIyzPnwVpNzdkfdHnci50SMIObVjcmX0PTdqA2ESMjXSM3xaXCGFTWMoDu4sjH+vpAfKJt6mtGLUiDlKYMoyqNBEs/j/RCfYtWDxD+ln8cFjXm5KCiB9QjnUJS8+aIPnWBYUG78XqpLu4rkwyMUVrHIhuf2vTDIzGP7XOH2FuBnKlaSujuB6UI+UD3fEnhjr4EmUvJeicwrlRdRQAB7omYr/L1eCMWQ2H038dGbLDBC6xmajNfQnzBPw7sgvRdO8KpsSWrfkXKvtTUNOad50Jq/EdegPRuavbLAzpn+suwyWq65yHd3xfPjDzj1ddXP7ipd7yzxpWgEdsiGmHZBo0SJa8+fBHrrpBvwbjud5phq35d+lStEEGXpzs1Lv5vDxIQOj88mY3hYt53oX9GNnRwH2P6JsGI4+sJNso4nwb0uaif3fPvxodZc1l1O2hf+TlsywKs+8dadF+a9W5eXv+JMH2oy8iL7yeJD4rtceeuQCPNBVQaVGZo+p47oQbiHNsOHrT3uQCBhwkvNbIVs3xnv/RJaX/MyFEI0Hcg=
  - secure: ncY60qs6CCQg0pIsbT4Hwo3NeN42uGHvx6c8pTr8wIic//SVYHz8LpTLPT5xisAcLU/ep+Qad1owhhW11qe/NV6gSicw/tsiXtJjVP+DBDSqHNKLzM51+HfwDdXFBllqS2esIs5G9hxsEDlmZK25OzqdhTLHmVXtiw5zfh7S5xOqdeuKPjIdCS583axyI3Cnm86l5ZKyw+7UEGqJCHwwVYDZCkM2qpDbd9m0JaLfpO/yx2ahwGt0X7ZhIedwI5/Z1RYx03udcc6iiJ+VlMznm8uql7QkHrz6Vs1j2JWjURMU9aoKT3AO+Yk08xBOY4BMXI9FRXu6JWmg/sKHXmWrOxBjNO3jA2xzsmwK5SQ9Z5jDsL2KK0GZyWE9i2OhMDO/jgM5LbPLa7W4clQT6SWAYxexkdyv+rVWMoID5yJVSVHD2RbV5blDCJa4UKgQbydBCnZPoEf3vM1s+hNVlWnFNq41tWa6hfvGeTyVvNZFZTRGo9+GdbIv2MM0KslhE4+uvkAI8UwI/UM+3fSqbaOiWeHxo/8V7g2vnNpTqM0xWTsJjMay42A+anLtzq7rez62vs5S7Of17wTK58tyLaqkiJFd9u69RDT2Bz6ZTi5CmE8En2/dfZEr5abr9Ay0ogVwxL4Sl7Owb4MoOwP04I+97B29cojSJDe+Ug2TT+4FEI8=
branches:
  only:
  - develop
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: contact@makemepulse.com
  api_key:
    secure: vKRDMCvwXOHzMBMguFki1QHZqbnTNaH8ms+WZ9FekE9yBaIcYl00yNNoka6urn0X+sDVCBi3XKkq1IXqa+6E70hB7CKuWgdCgo9bzxxxAQ9TJWe6a+uOUsTH//+eGOiL6mn7ASMmg/9HYRThFAiQBnSbOQTQP+onYNfcfmQUUprY+D35ZfyBi8t0xOFpmUgbmaK6RmPJvkLJhbR8ECHKb3CLAPrWwCp1p8PeROansWVBmTzQsOgS6uH4mk6hKrooVNiTFzwjU4RISUvNRHsiPhuPI5rkATn0jbQCZrMWrjH+FDPVoB8K22r0hBzcYII/H266ztVyG7RUWAMGgBdprtnaiqiaLw2D/ASJ9N6ig13AZZIHYpKNyq3W9aaZFfEsrYhXr+M9NeS4pYZ4ThUhYRzEW/rGzNTgHBlRB/ekYIAeZeDuhkGJTh/aoDeE8FMb4ybwQeHjDacPDeeLaj6rjAj51IHX//9wLFa7QCnpq74fUEehEnxZAs5Rzky2q5jHzdf6+J9LR9X/+7r7GdJBdOelRzOVuAUr7ZFlzGohyh4rzFY75jOiOuf66LjkH/tmAqOaa42+wof/CvgeDlyfkfkUPE68OJZAvXXiFq19lhyOaxBESp+UbkwIJHdchjF1qxh/CApoolT+5ZVqv2B3DCSvIilgG4Tt9QSVQaBa68Q=
  on:
    branch : master
    repo: plepers/nanogl-texture-loader
